spring.application.name=coreFlowShop

# 포트변경.  8080 기본포트로 사용하지만 현재 오라클시스템이 설치되어 있을 경우 문제가되어 변경한다. 
port=8888

# 브라우저 주소표시줄 URL에 jsessionid 노출안됨.
server.servlet.session.tracking-modes=cookie

# mysql 연결정보

# 개발용. log4jdbc라이브러리를 사용하기위한 데이타베이스 연결설정구문.
spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/fashionnova_db?serverTimezone=Asia/Seoul
spring.datasource.username=dev
spring.datasource.password=1234

# 배포용
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#mysql_main_url=jdbc:log4jdbc:mysql://localhost:3306/ezenshop?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
#mysql_main_username=test
#mysql_main_password=1234

#mybatis.mapper-locations=classpath:/mapper/*.xml



# 파일업로드 환경설정
# 업로드파일을 저장하는 형태. 1)DB 2)서버폴더(프로젝트 내부가 아닌 일반폴더) 3)클라우드- 예>aws에서 s3에 파일업로드
# 스프링부트 3.0 이전에서 파일업로드 라이브러리를 사용해야 했어음.

# 스프링부트 3.0 이상에서는 파일업로드 기능을 자체 지원함.
spring.servlet.multipart.enabled=true
# 임시파일경로
spring.servlet.multipart.location=C:/Dev/upload/pds
# 파일 1개의 최대크기
spring.servlet.multipart.max-file-size=10MB
# 전체파일의 최대크기
spring.servlet.multipart.max-request-size=100MB

# 서버측의 실제 업로드 경로(상품이미지).
com.coreflow.upload.path=C:/Dev/upload/pds
# CKEditor 에서 사용하는 상품설명이미지
com.coreflow.upload.ckeditor.path=C:/Dev/upload/ckeditor

#카카오 로그인
kakao.authorize=https://kauth.kakao.com/oauth/authorize
kakao.client_id=fa631220cbd0df9dde0e523f07abd8f5
kakao.redirect_uri=http://localhost:8888/member/kakao/callback
kakao.client_secret=l4hyoYVHdp9OFGUxSZX9IacBYpOvoncG

#카카오 로그아웃 주소
kakao.user.logout=https://kapi.kakao.com/v1/user/logout

#카카오 토큰발급
kakao.token_url=https://kauth.kakao.com/oauth/token


#카카오페이 API정보
readUrl=https://open-api.kakaopay.com/online/v1/payment/ready
approveUrl=https://open-api.kakaopay.com/online/v1/payment/approve 
secretKey=DEV225FAC4B51FFEFA5697B952A862618E4A9E37
cid=TC0ONETIME
approval=http://localhost:8888/kakao/approval
cancel=http://localhost:8888/kakao/cancel
fail=http://localhost:8888/kakao/fail


# kakaopay 정보
kakaosecretKey=DEV225FAC4B51FFEFA5697B952A862618E4A9E37
kakaocid=TC0ONETIME

# gmail 메일설정
# 구글 계정관리-보안- 앱비밀번호
emailusername=nuj27301@gmail.com
emailpassword=sowlawijrsejgsup

# chatbot
openai.api-key=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